[default_apps]
terminal = "wezterm"
browser = "/usr/bin/google-chrome-stable %U --new-window"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "F"
_currency = "usd"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock//icons/"]
icon_size = 22
search_icon = false
use_base_css = true
status_bar = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
cache = "~/.cache/sherlock/sherlock_desktop_cache.json"
caching = false
daemonize = false
animate = true

[binds]
prev = "control-p"
next = "control-n"

[files]
config = "~/.config/sherlock/config.toml"
css = "~/.config/sherlock/main.css"
fallback = "~/.config/sherlock/fallback.json"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
actions = "~/.config/sherlock/sherlock_actions.json"

[pipe]
