[default_apps]
terminal = "ghostty"
browser = "/usr/bin/vivaldi %U --new-window"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "F"
_currency = "usd"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
icon_paths = ["~/.config/sherlock//icons/"]
icon_size = 22
search_icon = false
use_base_css = true
status_bar = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
animate = true
global_prefix = "uwsm app --"

[binds]
up = "control-p"
down = "control-n"

[files]
config = "~/.config/sherlock/config.toml"
css = "~/.config/sherlock/main.css"
fallback = "~/.config/sherlock/fallback.json"
alias = "~/.config/sherlock/sherlock_alias.json"
ignore = "~/.config/sherlock/sherlockignore"
actions = "~/.config/sherlock/sherlock_actions.json"

[pipe]
